version: '3'
networks:
  mpstats:
services:
  app-admin:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql-mpstats
    networks:
      - mpstats

  mysql-mpstats:
    platform: linux/x86_64
    image: mariadb:10.6.16
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: mpstats
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - dbdata:/var/lib/mysql
    networks:
      - mpstats

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: root
    ports:
      - "8888:80"
    networks:
      - mpstats

  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - mpstats

  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php

  artisan:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql-mpstats
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - mpstats

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    environment:
      - REDIS_PORT=6379
    networks:
      - mpstats

#Volumes
volumes:
  dbdata:
    driver: local
  cache:
    driver: local
